name: issue to kanban
on:
  issues:
    types: [opened]

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: kanban
          column: To do
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
