name: issue to kanban
on:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      PROJECT: "kanban"
      COLUMN: "To do"
    outputs:
      out1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: $PROJECT
          column: $COLUMN
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
